# Generated by Django 4.2.5 on 2024-02-19 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_charge'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='currency',
            field=models.PositiveSmallIntegerField(choices=[(0, '$'), (1, '₽'), (2, '€')], default=0, verbose_name='Currency'),
        ),
    ]
