# Generated by Django 4.2.5 on 2024-02-25 07:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payments', '0002_charge'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('transaction_id', models.PositiveIntegerField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=6, default=0, max_digits=12)),
                ('currency', models.PositiveSmallIntegerField(choices=[(0, '$'), (1, '₽'), (2, '€')], default=1, verbose_name='Currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
