# Generated by Django 4.2.5 on 2024-02-25 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_userpayment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpayment',
            old_name='price',
            new_name='amount',
        ),
    ]
