# Generated by Django 4.2.5 on 2025-04-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_rename_price_userpayment_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='service_type',
            field=models.PositiveSmallIntegerField(choices=[(0, 'Other services'), (1, 'Self hosted radio service'), (2, 'Hosted radio stream (traffic)'), (3, 'Hosted radio disk usage'), (4, 'Text to speech')], default=0, verbose_name='Service type'),
        ),
    ]
