# Generated by Django 4.2.5 on 2023-10-20 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_balance_user_currency_user_language'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agreement_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
