# Generated by Django 4.2.5 on 2024-02-18 07:04

from django.db import migrations, models
import users.managers


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_agreement_accepted'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.managers.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='currency',
            field=models.PositiveSmallIntegerField(choices=[(0, '$'), (1, '₽'), (2, '€')], default=0, verbose_name='Currency'),
        ),
    ]
