# Generated by Django 4.2.5 on 2024-02-19 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_user_managers_alter_user_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='balance',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=12),
        ),
    ]
