# Generated by Django 4.2.5 on 2026-02-04 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0007_user_subscribed"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="stale_notification_sent_ts",
            field=models.DateTimeField(
                blank=True,
                help_text="When a stale-user notification was sent to this user.",
                null=True,
            ),
        ),
    ]
