# Generated by Django 4.2.5 on 2023-10-06 07:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RadioServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('nodename', models.CharField(max_length=255, verbose_name='Node subdomain name')),
                ('country', models.CharField(blank=True, max_length=255, null=True, verbose_name='Country')),
                ('provider', models.CharField(blank=True, max_length=255, null=True, verbose_name='Hosting provider')),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SelfHostedRadio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Radio station name')),
                ('ts_created', models.DateTimeField(auto_now_add=True, verbose_name='Creation timestamp')),
                ('domain', models.CharField(blank=True, max_length=255, null=True, verbose_name='Domain name')),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Pending'), (1, 'Checking'), (2, 'Ready')], default=0, verbose_name='Status')),
                ('is_blocked', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(verbose_name='IP Address')),
                ('root_password', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='SSH user password')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HostedRadio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Radio station name')),
                ('ts_created', models.DateTimeField(auto_now_add=True, verbose_name='Creation timestamp')),
                ('domain', models.CharField(blank=True, max_length=255, null=True, verbose_name='Domain name')),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Pending'), (1, 'Checking'), (2, 'Ready')], default=0, verbose_name='Status')),
                ('is_blocked', models.BooleanField(default=False)),
                ('comment', models.TextField(blank=True, null=True)),
                ('login', models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Hosting login name')),
                ('is_demo', models.BooleanField(default=False)),
                ('server', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='radio.radioserver')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
