# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 14:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Radio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Radio station name')),
                ('hosting', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Self-hosted'), (1, 'Hosted')], default=1, verbose_name='Hosting')),
                ('ts_created', models.DateTimeField(auto_now_add=True, verbose_name='Creation timestamp')),
                ('status', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Pending'), (1, 'Checking'), (2, 'Ready')], default=0, verbose_name='Status')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('domain', models.CharField(blank=True, max_length=255, null=True, verbose_name='Domain name')),
                ('login', models.CharField(blank=True, max_length=255, null=True, verbose_name='Hosting login name')),
            ],
        ),
        migrations.CreateModel(
            name='RadioServer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP address')),
                ('nodename', models.CharField(max_length=255, verbose_name='Node subdomain name')),
                ('country', models.CharField(blank=True, max_length=255, null=True, verbose_name='Country')),
                ('provider', models.CharField(blank=True, max_length=255, null=True, verbose_name='Hosting provider')),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='radio',
            name='server',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='radio.RadioServer'),
        ),
        migrations.AddField(
            model_name='radio',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
    ]
