# Generated by Django 4.2.5 on 2024-02-19 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0002_alter_hostedradioservice_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfhostedradio',
            name='custom_price',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=12, null=True),
        ),
    ]
