# Generated by Django 4.2.5 on 2023-10-20 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0002_remove_selfhostedradio_root_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfhostedradio',
            name='ssh_password',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='SSH user password'),
        ),
    ]
