# Generated by Django 4.2.5 on 2023-11-03 16:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0003_selfhostedradio_ssh_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostedradio',
            name='initial_audio_format',
            field=models.CharField(blank=True, choices=[(0, 'Mp3'), (1, 'AAC++'), (2, 'FLAC')], max_length=10, null=True, verbose_name='Audio format'),
        ),
        migrations.AddField(
            model_name='hostedradio',
            name='initial_bitrate',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Bitrate'),
        ),
        migrations.AddField(
            model_name='hostedradio',
            name='initial_du',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Disk quota'),
        ),
        migrations.AddField(
            model_name='hostedradio',
            name='initial_listeners',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Maximum number of listeners'),
        ),
        migrations.AlterField(
            model_name='hostedradio',
            name='login',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True, validators=[django.core.validators.RegexValidator('^[a-z_]([a-z0-9_-]{0,31}|[a-z0-9_-]{0,30}\\$)$')], verbose_name='Hosting login name'),
        ),
    ]
