# Generated by Django 4.2.5 on 2024-02-21 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0003_alter_selfhostedradio_custom_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='PortRegistry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.PositiveIntegerField(blank=True, null=True)),
                ('dj_id', models.PositiveIntegerField(blank=True, null=True)),
                ('port', models.PositiveIntegerField()),
                ('server_type', models.CharField(blank=True, max_length=20, null=True)),
                ('mount', models.CharField(blank=True, max_length=255, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('radio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.hostedradio')),
            ],
        ),
    ]
