# Generated by Django 4.2.5 on 2024-02-17 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0004_hostedradio_initial_audio_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostedradio',
            name='debug_msg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='selfhostedradio',
            name='debug_msg',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hostedradio',
            name='initial_audio_format',
            field=models.CharField(blank=True, choices=[('mp3', 'Mp3'), ('aac++', 'AAC++'), ('flac', 'FLAC')], max_length=10, null=True, verbose_name='Audio format'),
        ),
        migrations.AlterField(
            model_name='hostedradio',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Pending'), (1, 'Checking'), (2, 'Ready'), (3, 'Being created'), (4, 'Being deleted'), (5, 'Suspended'), (6, 'Error')], default=0, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='selfhostedradio',
            name='status',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Pending'), (1, 'Checking'), (2, 'Ready'), (3, 'Being created'), (4, 'Being deleted'), (5, 'Suspended'), (6, 'Error')], default=0, verbose_name='Status'),
        ),
    ]
