# Generated by Django 4.2.5 on 2024-02-22 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0005_alter_portregistry_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='radioserver',
            name='nodename',
            field=models.CharField(max_length=255, unique=True, verbose_name='Node subdomain name'),
        ),
    ]
