# Generated by Django 4.2.5 on 2024-02-18 06:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0005_hostedradio_debug_msg_selfhostedradio_debug_msg_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HostedRadioService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.PositiveSmallIntegerField(choices=[('mp3', 'Mp3'), ('aac++', 'AAC++'), ('flac', 'FLAC')], verbose_name='Service type')),
                ('channel_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Stream channel ID')),
                ('bitrate', models.PositiveIntegerField(blank=True, null=True, verbose_name='Bitrate')),
                ('listeners', models.PositiveIntegerField(blank=True, null=True, verbose_name='Maximum number of listeners')),
                ('du', models.PositiveIntegerField(blank=True, null=True, verbose_name='Disk quota')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('radio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.hostedradio')),
            ],
        ),
    ]
