# Generated by Django 4.2.5 on 2024-02-22 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0006_alter_radioserver_nodename'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostedradio',
            name='disk_usage',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Disk usage'),
        ),
    ]
