# Generated by Django 4.2.5 on 2024-02-23 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0007_hostedradio_disk_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfhostedradio',
            name='is_unbranded',
            field=models.BooleanField(default=False),
        ),
    ]
