# Generated by Django 4.2.5 on 2024-02-18 07:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0007_selfhostedradio_custom_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostedradio',
            name='server',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='radio.radioserver'),
        ),
    ]
