# Generated by Django 4.2.5 on 2024-02-25 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0008_selfhostedradio_is_unbranded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostedradioservice',
            name='radio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='radio.hostedradio'),
        ),
        migrations.AlterField(
            model_name='hostedradioservice',
            name='service_type',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Stream traffic'), (2, 'Disk usage')], verbose_name='Service type'),
        ),
    ]
