# Generated by Django 4.2.5 on 2024-02-27 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0009_alter_hostedradioservice_radio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostedradio',
            name='copyright_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Has legal documents'), (2, 'No copyrighted content is used'), (3, 'Test account')], null=True, verbose_name='Copyright settings'),
        ),
    ]
