# Generated by Django 4.2.5 on 2024-03-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0010_hostedradio_copyright_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selfhostedradio',
            name='ip',
            field=models.GenericIPAddressField(unique=True, verbose_name='IP Address'),
        ),
    ]
