# Generated by Django 4.2.5 on 2024-04-04 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0013_alter_hostedradio_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfhostedradio',
            name='radios_num',
            field=models.PositiveIntegerField(default=0, verbose_name='The number of radios on the server'),
        ),
    ]
