# Generated by Django 4.2.5 on 2024-05-23 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("radio", "0014_selfhostedradio_radios_num"),
    ]

    operations = [
        migrations.AddField(
            model_name="hostedradio",
            name="custom_price",
            field=models.DecimalField(
                blank=True, decimal_places=6, max_digits=12, null=True
            ),
        ),
    ]
