# Generated by Django 4.2.5 on 2025-02-19 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0016_hostedradio_branded_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='selfhostedradio',
            name='fixed_version',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Fixed version number (for old lifetime licenses)'),
        ),
    ]
