# Generated by Django 4.2.5 on 2025-03-15 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radio', '0017_selfhostedradio_fixed_version'),
    ]

    operations = [
        migrations.CreateModel(
            name='RadioSocialLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('website', 'Website'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('watsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('phone', 'Phone'), ('email', 'Email'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('pinterest', 'Pinterest'), ('snapchat', 'Snapchat'), ('reddit', 'Reddit'), ('discord', 'Discord'), ('wechat', 'WeChat'), ('x', 'X'), ('twitch', 'Twitch'), ('vk', 'VK'), ('rutube', 'RuTube'), ('ok', 'Odnoklassniki')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('value', models.CharField(max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
    ]
