# Generated by Django 4.2.5 on 2024-03-04 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_application', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='androidapplication',
            name='build_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='androidapplication',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Player user-agent'),
        ),
        migrations.AddField(
            model_name='iosapplication',
            name='build_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='iosapplication',
            name='user_agent',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Player user-agent'),
        ),
    ]
