# Generated by Django 4.2.5 on 2024-03-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_application', '0002_androidapplication_build_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='androidapplication',
            name='package_name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
