# Generated by Django 4.2.5 on 2024-03-16 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_application', '0003_androidapplication_package_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='androidapplicationradiochannel',
            name='audio_format',
            field=models.CharField(choices=[('mp3', 'Mp3'), ('aac', 'AAC'), ('flac', 'FLAC')], default='mp3', max_length=10, verbose_name='Audio format'),
        ),
        migrations.AlterField(
            model_name='iosapplicationradiochannel',
            name='audio_format',
            field=models.CharField(choices=[('mp3', 'Mp3'), ('aac', 'AAC'), ('flac', 'FLAC')], default='mp3', max_length=10, verbose_name='Audio format'),
        ),
    ]
