# Generated by Django 4.2.5 on 2024-03-29 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_application', '0004_alter_androidapplicationradiochannel_audio_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='iosapplication',
            name='package_name',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
