# Generated by Django 4.2.5 on 2025-01-31 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_application', '0006_androidapplicationradiochannel_encoding_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='androidapplication',
            name='is_sc_publishing',
        ),
        migrations.RemoveField(
            model_name='iosapplication',
            name='is_sc_publishing',
        ),
        migrations.AddField(
            model_name='androidapplication',
            name='publication_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Streaming.Center developer account'), (1, 'Third party developer account'), (2, 'No need to publish the app')], default=0, null=True),
        ),
        migrations.AddField(
            model_name='iosapplication',
            name='publication_type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(0, 'Streaming.Center developer account'), (1, 'Third party developer account'), (2, 'No need to publish the app')], default=0, null=True),
        ),
    ]
