# Generated by Django 4.2.5 on 2025-03-15 14:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_application', '0008_androidapplication_created_iosapplication_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='IosSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('website', 'Website'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('watsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('phone', 'Phone'), ('email', 'Email'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('pinterest', 'Pinterest'), ('snapchat', 'Snapchat'), ('reddit', 'Reddit'), ('discord', 'Discord'), ('wechat', 'WeChat'), ('x', 'X'), ('twitch', 'Twitch'), ('vk', 'VK'), ('rutube', 'RuTube'), ('ok', 'Odnoklassniki')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('value', models.CharField(max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('radio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='mobile_application.iosapplicationradio')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AndroidSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('website', 'Website'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('watsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('phone', 'Phone'), ('email', 'Email'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('pinterest', 'Pinterest'), ('snapchat', 'Snapchat'), ('reddit', 'Reddit'), ('discord', 'Discord'), ('wechat', 'WeChat'), ('x', 'X'), ('twitch', 'Twitch'), ('vk', 'VK'), ('rutube', 'RuTube'), ('ok', 'Odnoklassniki')], max_length=20)),
                ('title', models.CharField(blank=True, max_length=20, null=True)),
                ('value', models.CharField(max_length=255)),
                ('order', models.PositiveSmallIntegerField(default=0)),
                ('radio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='mobile_application.androidapplicationradio')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
