# Generated by Django 4.2.5 on 2025-04-05 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_application', '0009_iossociallink_androidsociallink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='androidsociallink',
            name='type',
            field=models.CharField(choices=[('website', 'Website'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('phone', 'Phone'), ('email', 'Email'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('pinterest', 'Pinterest'), ('snapchat', 'Snapchat'), ('reddit', 'Reddit'), ('discord', 'Discord'), ('wechat', 'WeChat'), ('x', 'X'), ('twitch', 'Twitch'), ('vk', 'VK'), ('rutube', 'RuTube'), ('ok', 'Odnoklassniki')], max_length=20),
        ),
        migrations.AlterField(
            model_name='iossociallink',
            name='type',
            field=models.CharField(choices=[('website', 'Website'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('phone', 'Phone'), ('email', 'Email'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('pinterest', 'Pinterest'), ('snapchat', 'Snapchat'), ('reddit', 'Reddit'), ('discord', 'Discord'), ('wechat', 'WeChat'), ('x', 'X'), ('twitch', 'Twitch'), ('vk', 'VK'), ('rutube', 'RuTube'), ('ok', 'Odnoklassniki')], max_length=20),
        ),
    ]
