# Generated by Django 4.2.5 on 2025-04-28 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_application', '0010_alter_androidsociallink_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='androidapplication',
            name='use_mirror',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='iosapplication',
            name='use_mirror',
            field=models.BooleanField(default=False),
        ),
    ]
