# Generated by Django 4.2.5 on 2025-05-19 13:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("mobile_application", "0011_androidapplication_use_mirror_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="iOsRadioPreroll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="prerolls", verbose_name="Radio preroll"
                    ),
                ),
                (
                    "radio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prerolls",
                        to="mobile_application.iosapplicationradio",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="AndroidRadioPreroll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to="prerolls", verbose_name="Radio preroll"
                    ),
                ),
                (
                    "radio",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prerolls",
                        to="mobile_application.androidapplicationradio",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
