# Generated by Django 4.2.5 on 2025-05-21 14:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("mobile_application", "0012_iosradiopreroll_androidradiopreroll"),
    ]

    operations = [
        migrations.AddField(
            model_name="androidapplicationradio",
            name="prerolls_update_ts",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="iosapplicationradio",
            name="prerolls_update_ts",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
