# Generated by Django 4.2.5 on 2025-11-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mobile_application", "0014_iosprerollimpression_androidprerollimpression"),
    ]

    operations = [
        migrations.AddField(
            model_name="androidapplicationradio",
            name="allow_history",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="iosapplicationradio",
            name="allow_history",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="androidapplicationradiochannel",
            name="server_type",
            field=models.CharField(
                choices=[
                    ("shoutcast", "Shoutcast"),
                    ("icecast", "Icecast"),
                    ("hls", "HLS"),
                    ("other", "Other"),
                ],
                default="shoutcast",
                max_length=20,
                verbose_name="Server type",
            ),
        ),
        migrations.AlterField(
            model_name="iosapplicationradiochannel",
            name="server_type",
            field=models.CharField(
                choices=[
                    ("shoutcast", "Shoutcast"),
                    ("icecast", "Icecast"),
                    ("hls", "HLS"),
                    ("other", "Other"),
                ],
                default="shoutcast",
                max_length=20,
                verbose_name="Server type",
            ),
        ),
    ]
