# Generated by Django 4.2.5 on 2026-06-04 11:41

from django.db import migrations, models


def set_existing_app_versions_to_v1(apps, schema_editor):
    AndroidApplication = apps.get_model('mobile_application', 'AndroidApplication')
    IosApplication = apps.get_model('mobile_application', 'IosApplication')

    AndroidApplication.objects.update(version='v1.0')
    IosApplication.objects.update(version='v1.0')


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_application', '0015_androidapplicationradio_allow_history_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='androidapplication',
            name='version',
            field=models.CharField(choices=[('v1.0', 'Version 1.0 (Older design)'), ('v2.0', 'Version 2.0 (New design)')], default='v2.0', max_length=10),
        ),
        migrations.AlterField(
            model_name='androidsociallink',
            name='type',
            field=models.CharField(choices=[('website', 'Website'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('phone', 'Phone'), ('email', 'Email'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('pinterest', 'Pinterest'), ('snapchat', 'Snapchat'), ('reddit', 'Reddit'), ('discord', 'Discord'), ('wechat', 'WeChat'), ('x', 'X'), ('twitch', 'Twitch'), ('vk', 'VK'), ('rutube', 'RuTube'), ('ok', 'Odnoklassniki'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='iosapplication',
            name='version',
            field=models.CharField(choices=[('v1.0', 'Version 1.0 (Older design)'), ('v2.0', 'Version 2.0 (New design)')], default='v2.0', max_length=10),
        ),
        migrations.RunPython(
            set_existing_app_versions_to_v1,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='iossociallink',
            name='type',
            field=models.CharField(choices=[('website', 'Website'), ('instagram', 'Instagram'), ('facebook', 'Facebook'), ('youtube', 'YouTube'), ('whatsapp', 'WhatsApp'), ('telegram', 'Telegram'), ('phone', 'Phone'), ('email', 'Email'), ('linkedin', 'LinkedIn'), ('tiktok', 'TikTok'), ('pinterest', 'Pinterest'), ('snapchat', 'Snapchat'), ('reddit', 'Reddit'), ('discord', 'Discord'), ('wechat', 'WeChat'), ('x', 'X'), ('twitch', 'Twitch'), ('vk', 'VK'), ('rutube', 'RuTube'), ('ok', 'Odnoklassniki'), ('other', 'Other')], max_length=20),
        ),
    ]
