# Generated by Django 4.2.5 on 2026-07-07 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_application', '0017_restore_version_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='androidapplication',
            name='allow_countdown_timer',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='iosapplication',
            name='allow_countdown_timer',
            field=models.BooleanField(default=True),
        ),
    ]
