# Generated by Django 4.2.5 on 2026-07-10 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mobile_application', '0018_androidapplication_allow_countdown_timer_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='androidapplication',
            name='allow_countdown_timer',
        ),
        migrations.RemoveField(
            model_name='iosapplication',
            name='allow_countdown_timer',
        ),
    ]
