# Generated by Django 4.2.5 on 2025-09-06 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="name_eng",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="genre",
            name="name_eng",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="language",
            name="name_eng",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
