# Generated by Django 4.2.5 on 2025-09-09 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_radio_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="city",
            name="country",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cities",
                to="catalog.country",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="city",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="city",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="city",
            name="name",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="city",
            name="name_eng",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="name",
            field=models.CharField(max_length=64, unique=True),
        ),
        migrations.AlterField(
            model_name="country",
            name="name_eng",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="region",
            name="name",
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name="region",
            name="name_eng",
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
