# Generated by Django 4.2.5 on 2025-09-09 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_city_country_city_latitude_city_longitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="city",
            name="region",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cities",
                to="catalog.region",
            ),
        ),
    ]
