# Generated by Django 4.2.5 on 2025-09-11 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0006_alter_city_region"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stream",
            old_name="url",
            new_name="stream_url",
        ),
        migrations.AddField(
            model_name="stream",
            name="server_type",
            field=models.CharField(
                choices=[
                    ("shoutcast", "Shoutcast"),
                    ("icecast", "Icecast"),
                    ("hls", "HLS"),
                ],
                default="shoutcast",
                max_length=20,
                verbose_name="Server type",
            ),
        ),
    ]
