# Generated by Django 4.2.5 on 2025-09-11 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0007_rename_url_stream_stream_url_stream_server_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="radio",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
