# Generated by Django 4.2.5 on 2025-09-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_radio_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="stream",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="stream",
            name="server_type",
            field=models.CharField(
                choices=[
                    ("shoutcast", "Shoutcast"),
                    ("icecast", "Icecast"),
                    ("hls", "HLS"),
                    ("other", "Other"),
                ],
                default="shoutcast",
                max_length=20,
                verbose_name="Server type",
            ),
        ),
    ]
