# Generated by Django 4.2.5 on 2025-09-18 06:17

from django.db import migrations, models
import django.utils.timezone
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_stream_enabled_alter_stream_server_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="radio",
            options={"get_latest_by": "modified"},
        ),
        migrations.AlterModelOptions(
            name="stream",
            options={"get_latest_by": "modified"},
        ),
        migrations.RemoveField(
            model_name="radio",
            name="average_rating",
        ),
        migrations.AddField(
            model_name="radio",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="radio",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, verbose_name="modified"
            ),
        ),
        migrations.AddField(
            model_name="radio",
            name="total_score",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="stream",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="stream",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, verbose_name="modified"
            ),
        ),
        migrations.AddField(
            model_name="vote",
            name="created",
            field=django_extensions.db.fields.CreationDateTimeField(
                auto_now_add=True,
                default=django.utils.timezone.now,
                verbose_name="created",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="vote",
            name="modified",
            field=django_extensions.db.fields.ModificationDateTimeField(
                auto_now=True, verbose_name="modified"
            ),
        ),
    ]
