# Generated by Django 4.2.5 on 2025-09-19 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_alter_radio_options_alter_stream_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="iso2",
            field=models.CharField(blank=True, max_length=2, null=True, unique=True),
        ),
    ]
