# Generated by Django 4.2.5 on 2025-09-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_country_iso2"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="vote",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="vote",
            name="ip",
            field=models.GenericIPAddressField(default=None, verbose_name="IP address"),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="vote",
            unique_together={("radio", "ip")},
        ),
        migrations.RemoveField(
            model_name="vote",
            name="rating",
        ),
        migrations.RemoveField(
            model_name="vote",
            name="user",
        ),
    ]
